# Generated by Django 2.1.1 on 2020-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=225)),
                ('order', models.IntegerField(default=0)),
                ('choice1', models.CharField(blank=True, max_length=255)),
                ('choice2', models.CharField(blank=True, max_length=255)),
                ('choice3', models.CharField(blank=True, max_length=255)),
                ('choice4', models.CharField(blank=True, max_length=255)),
                ('correctAnswer', models.CharField(max_length=255)),
            ],
        ),
    ]
